name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/recs-mlops
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install fastapi "uvicorn[standard]" redis faiss-cpu pydantic pytest

      - name: Run tests
        run: pytest -q

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} -f infra/docker/Dockerfile .

      - name: Push image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Set image tag output
        id: meta
        run: echo "image=$IMAGE_NAME:${{ github.sha }}" >> $GITHUB_OUTPUT