name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: IMAGE_NAME variable
        run: |
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}/hybrid-recommender" >>${GITHUB_ENV}
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main 
        with:
          role-to-assume: arn:aws:iam::671516769969:role/github-action-role
          aws-region: us-east-1

      - name: Pull data with DVC
        run: |
          python -m pip install -U pip
          pip install "dvc[s3]"
          dvc pull -v

      - name: Run tests
        run: |
          pip install -U pip
          pip install fastapi "uvicorn[standard]" pytest numpy pydantic joblib redis
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
          pytest -q

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} -f infra/docker/Dockerfile .

      - name: Push image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Set image tag output
        id: meta
        run: echo "image=$IMAGE_NAME:${{ github.sha }}" >> $GITHUB_OUTPUT